### ISSUE TITLE
Unknown mat file type

### ISSUE THREAD

**Issue by captaman** [gigascience/paper-bray2017#4]
Whenever I try to load the pipelines in CellProfiler (v3.1.8 on Windows) I get an error "Error while loading None: Unknown mat file type, version 98, 46 Do you want to stop processing?" The command line running CellProfiler also says:

```
> Tried to load corrupted .MAT file: C:\Users\user\Downloads\illum.cppipe
> Traceback (most recent call last):
>   File "CellProfiler\cellprofiler\pipeline.py", line 822, in load
>   File "site-packages\scipy\io\matlab\mio.py", line 141, in loadmat
>   File "site-packages\scipy\io\matlab\mio.py", line 65, in mat_reader_factory
>   File "site-packages\scipy\io\matlab\miobase.py", line 241, in get_matfile_version
> ValueError: Unknown mat file type, version 98, 46
```

I tried using CellProfiler 2.1.1 but I still got similar errors.

**Comment by ScottBGI** [comment]
Has @shntnu seen this issue?

**Comment by LTYUnique** [comment]
Did you resolve this problem? I got similar errors.

**Comment by captaman** [comment]
I recently got it to work. I reinstalled Python and Java on my system and then reinstalled CP. After that it started working, not sure what the exact issue was.

**Comment by shntnu** [comment]
@captaman @LTYUnique I wasn't able to reproduce that error – I tried with CellProfiler 2.2.0 just now and it worked ok. But indeed these pipelines are not compatible with CellProfiler 3. See [this](https://blog.cellprofiler.org/2017/10/24/the-cellprofiler-2-users-guide-to-cellprofiler-3-0-part-ii-converting-your-pipelines/) blog post.

If you still have issues with this, I'd suggest posting on https://forum.image.sc/tags/cellprofiler because you are likely to get much quicker responses on the forum (be sure to tag the post with `cellprofiler`)
